title: woohongseok
description: "woohongseok's dev blog"
baseurl: "/blog"
url: "https://woohongseok.github.io"

google_analytics: G-N0LNG5VM0D

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
