title: woohongseok
description: "woohongseok's dev blog"
baseurl: "/blog"
url: "https://woohongseok.github.io"

# google_analytics: G-XXXXXXXXXX

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
